#!/bin/bash

# the dollar sign pound will be 0 if no arguments are passed to the script on the command line.
E_NO_ARGS=65

if [ $# -eq 0 ]  # Must have command-line args to demo script.
then
  echo "Please invoke this script with one or more command-line arguments."
  exit $E_NO_ARGS
else
echo "my number is $1"
fi  
